title: Learning blog
author: Vamik
email: mohd.vamik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi Team, this is my learing blog where i start my to share my learing of **python, database, java** so on.
 Hi Team, this is my learing blog where i start my to share my learing of **python, database, java** so on.
 Hi Team, this is my learing blog where i start my to share my learing of **python, database, java** so on.
 Hi Team, this is my learing blog where i start my to share my learing of **python, database, java** so on.
 Hi Team, this is my learing blog where i start my to share my learing of **python, database, java** so on.

# social links
twitter_username: mohd-vamik # DO NOT include the @ character, or else the build will fail!
github_username:  Imvamik # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
